### ISSUE TITLE
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Unknown animation

### ISSUE THREAD

**Issue by exaxeeae** [SolarLune/bdx#27] opened 2018-04-07 13:19 UTC
i cant play 3D animation ; BDX cant find my ; excuse my English

**Comment by rafcolson** [comment] 2018-04-09 16:12
This probably is a duplicate of https://github.com/GoranM/bdx/issues/1042

**Comment by SolarLune** [comment] 2018-04-23 14:33
Yeah, I'd guess so. 

Please feel free to report bugs on the "original master", on Goran's branch.

**Closed as completed by SolarLune** 2018-04-23 14:33 UTC
